server:
  port: 27890
  servlet:
    context-path: /api

spring:
  application:
    name: bitspark-share-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.32.244.148:3306/mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: camellia20.


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: idDeleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

knife4j:
  enable: true
  openapi:
    title: Bispark Share API
    description: "BitSpark Copyright - 数字火花版权"
    email: camellia.xiaohua@gmail.com
    concat: CAMELLIA
    url: https://docs.xiaominfo.com
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        group-name: BitSpark
        api-rule: package
        api-rule-resources:
          - com.bitspark.controller